# Generated by Django 5.0.6 on 2024-05-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=200)),
                ("photo_url", models.TextField()),
                ("phone_no", models.JSONField()),
                ("email", models.JSONField()),
            ],
        ),
    ]
