# Generated by Django 5.0.6 on 2024-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_rename_photo_url_contact_photo_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="full_name",
            field=models.JSONField(),
        ),
    ]
