# Generated by Django 5.0.6 on 2024-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contact_photo_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="photo_path",
            field=models.TextField(),
        ),
    ]
