# Generated by Django 5.0.6 on 2024-05-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_contact_photo_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="photo_path",
            new_name="photo_path_url",
        ),
    ]
