# Generated by Django 5.0.6 on 2024-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_rename_photo_path_contact_photo_path_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="photo_path_url",
            new_name="photo_path",
        ),
    ]
